{% set python_min = '3.10' %}
{% set name = "openmmforcefields" %}
{% set version = "0.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openmm/openmmforcefields/archive/{{ version }}.tar.gz
  sha256: 9600d35d5be4795c203d53eae24105f92e1d852be30e1348d99060f1b2333498

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - ambertools >=22,<25
    - lxml
    - networkx
    - openff-interchange >=0.4  # if we need 0.3, can relax later
    - openff-toolkit >=0.16.1
    - openff-units >=0.2
    - openmm >=7.6.0
    - python >={{ python_min }}
    - pyyaml
    - tinydb
    - validators

  run_constrained:
    - espaloma >=0.3.2
    - openforcefield =9999999999999

test:
  imports:
    - openmmforcefields
  requires:
    - pytest
    - pytest-xdist
    - python {{ python_min }}
  commands:
    - pytest -v -n logical --pyargs openmmforcefields

about:
  home: http://openmm.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Extra support for additional forcefields in OpenMM
  description: |
    Support for AMBER and CHARMM force fields and small molecule
    parameterization with GAFF and the Open Force Field Toolkit
    for OpenMM.
  doc_url: http://docs.openmm.org/
  dev_url: https://github.com/openmm/openmmforcefields

extra:
  recipe-maintainers:
    - jaimergp
    - jchodera
    - peastman
    - mikemhenry
    - ijpulidos
    - mattwthompson
