schema_version: 1

context:
  python_min: 3.11
  name: openmmforcefields
  version: 0.15.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/openmm/openmmforcefields/archive/${{ version }}.tar.gz
  sha256: c13e3c88e84cca182ee24bdfe2e4b805ed7b9e1e4f34a960af03ac03eb08ae88

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - importlib_resources
    - ambertools >=22,<25
    - lxml
    - networkx
    - numpy
    - openff-interchange >=0.4  # if we need 0.3, can relax later
    - openff-toolkit >=0.16.1
    - openff-units >=0.2
    - openmm >=8.1.2
    - python >=${{ python_min }}
    - pyyaml
    - tinydb
    - validators
  run_constraints:
    - espaloma >=0.3.2
    - openforcefield =9999999999999
    - parmed >= 4.3.1

tests:
  - python:
      imports:
        - openmmforcefields
      pip_check: false
      python_version: ${{ python_min }}.*

  - requirements:
      run:
        - pytest
        - pytest-xdist
        - python ${{ python_min }}.*
        - smirnoff99frosst
    script:
      - pytest -v -n logical --pyargs openmmforcefields

about:
  license: MIT
  license_file: LICENSE
  summary: Extra support for additional forcefields in OpenMM
  description: |
    Support for AMBER and CHARMM force fields and small molecule
    parameterization with GAFF and the Open Force Field Toolkit
    for OpenMM.
  homepage: http://openmm.org/
  repository: https://github.com/openmm/openmmforcefields
  documentation: http://docs.openmm.org/

extra:
  recipe-maintainers:
    - jaimergp
    - jchodera
    - peastman
    - mikemhenry
    - ijpulidos
    - mattwthompson
